import * as type from '../constants/events';

const initialState = {
  pagination: {
    object_count: 41,
    page_number: 1,
    page_size: 50,
    page_count: 1,
    has_more_items: false,
  },
  events: [
    {
      name: {
        text: 'Rosinka ASA Tuesday Years 1-3 ',
        html: 'Rosinka ASA Tuesday Years 1-3 ',
      },
      description: {
        text: 'ROSINKA\u00a0Tuesday After School Activities for all students\u00a0in\u00a0Years 1-3\u00a0will start at 15:30 and end at 16:30. The first date of the club is Tuesday 16th January and the last date is Tuesday 13 March 2018. Please click on the club for more details to see if PE kits need to be worn or which equipment you are required to bring.\n\u00a0\nFull descriptions are not available when viewing on an ipad, so please ensure you view on another device.',
        html: '<P CLASS="MsoNormal"><SPAN>ROSINKA\u00a0Tuesday After School Activities for all students\u00a0in\u00a0Years 1-3\u00a0will start at 15:30 and end at 16:30. The first date of the club is Tuesday 16th January and the last date is Tuesday 13 March 2018. Please click on the club for more details to see if PE kits need to be worn or which equipment you are required to bring.<\/SPAN><SPAN><\/SPAN><\/P>\n<P CLASS="MsoNormal"><SPAN>\u00a0<\/SPAN><\/P>\n<P CLASS="MsoNormal"><SPAN>Full descriptions are not available when viewing on an ipad, so please ensure you view on another device.<\/SPAN><\/P>',
      },
      id: '41056065798',
      url: 'https://www.eventbrite.com/e/rosinka-asa-tuesday-years-1-3-tickets-41056065798?aff=ebapi',
      start: {
        timezone: 'Europe/Moscow',
        local: '2018-01-16T15:30:00',
        utc: '2018-01-16T12:30:00Z',
      },
      end: {
        timezone: 'Europe/Moscow',
        local: '2018-03-13T16:30:00',
        utc: '2018-03-13T13:30:00Z',
      },
      created: '2017-12-05T19:37:35Z',
      changed: '2017-12-11T06:28:41Z',
      capacity: 104,
      capacity_is_custom: true,
      status: 'live',
      currency: 'USD',
      listed: true,
      shareable: true,
      online_event: false,
      tx_time_limit: 480,
      hide_start_date: false,
      hide_end_date: false,
      locale: 'en_US',
      is_locked: false,
      privacy_setting: 'unlocked',
      is_series: false,
      is_series_parent: false,
      is_reserved_seating: false,
      source: 'create_2.0',
      is_free: false,
      version: '3.0.0',
      logo_id: '38426517',
      organizer_id: '2966850589',
      venue_id: '19368286',
      category_id: null,
      subcategory_id: null,
      format_id: null,
      resource_uri: 'https://www.eventbriteapi.com/v3/events/41056065798/',
      logo: {
        crop_mask: {
          top_left: {
            x: 0,
            y: 6,
          },
          width: 254,
          height: 127,
        },
        original: {
          url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F38426517%2F116239082455%2F1%2Foriginal.jpg?s=4476de2af3dc5e185abedccee02a96df',
          width: 255,
          height: 196,
        },
        id: '38426517',
        url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F38426517%2F116239082455%2F1%2Foriginal.jpg?h=200&w=450&rect=0%2C6%2C254%2C127&s=0925db7212d31a465201eeaaf8b4120c',
        aspect_ratio: '2',
        edge_color: null,
        edge_color_set: true,
      },
    },
    {
      name: {
        text: 'Rosinka ASA Wednesday Years 4-6',
        html: 'Rosinka ASA Wednesday Years 4-6',
      },
      description: {
        text: 'ROSINKA\u00a0Wednesday After School Activities for all students\u00a0in\u00a0Years 4-6\u00a0will start at 15:30 and end at 16:30. The first date of the club is Wednesday 17th January and the last date is Wednesday 14th March 2018. Please click on the club for more details to see if PE kits need to be worn or which equipment you are required to bring.\n\u00a0Full descriptions are not available when viewing on an ipad, so please ensure you view on another device.\n\u00a0',
        html: '<P CLASS="MsoNormal"><SPAN>ROSINKA\u00a0Wednesday After School Activities for all students\u00a0in\u00a0Years 4-6\u00a0will start at 15:30 and end at 16:30. The first date of the club is Wednesday 17th January and the last date is Wednesday 14th March 2018. Please click on the club for more details to see if PE kits need to be worn or which equipment you are required to bring.<\/SPAN><SPAN><\/SPAN><\/P>\n<P CLASS="MsoNormal"><SPAN>\u00a0<\/SPAN>Full descriptions are not available when viewing on an ipad, so please ensure you view on another device.<\/P>\n<P CLASS="MsoNormal">\u00a0<\/P>',
      },
      id: '41057338605',
      url: 'https://www.eventbrite.com/e/rosinka-asa-wednesday-years-4-6-tickets-41057338605?aff=ebapi',
      start: {
        timezone: 'Europe/Moscow',
        local: '2018-01-17T15:30:00',
        utc: '2018-01-17T12:30:00Z',
      },
      end: {
        timezone: 'Europe/Moscow',
        local: '2018-03-14T16:30:00',
        utc: '2018-03-14T13:30:00Z',
      },
      created: '2017-12-05T20:06:13Z',
      changed: '2017-12-11T06:32:06Z',
      capacity: 88,
      capacity_is_custom: true,
      status: 'live',
      currency: 'USD',
      listed: true,
      shareable: true,
      online_event: false,
      tx_time_limit: 480,
      hide_start_date: false,
      hide_end_date: false,
      locale: 'en_US',
      is_locked: false,
      privacy_setting: 'unlocked',
      is_series: false,
      is_series_parent: false,
      is_reserved_seating: false,
      source: 'create_2.0',
      is_free: true,
      version: '3.0.0',
      logo_id: '38427839',
      organizer_id: '2966850589',
      venue_id: '19368286',
      category_id: null,
      subcategory_id: null,
      format_id: null,
      resource_uri: 'https://www.eventbriteapi.com/v3/events/41057338605/',
      logo: {
        crop_mask: {
          top_left: {
            x: 0,
            y: 6,
          },
          width: 254,
          height: 127,
        },
        original: {
          url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F38427839%2F116239082455%2F1%2Foriginal.jpg?s=09d1e2d6c9c6246fc3d66555ac670f2a',
          width: 255,
          height: 196,
        },
        id: '38427839',
        url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F38427839%2F116239082455%2F1%2Foriginal.jpg?h=200&w=450&rect=0%2C6%2C254%2C127&s=a2e9d5ef8401d50eeae6be3cc43cb179',
        aspect_ratio: '2',
        edge_color: null,
        edge_color_set: true,
      },
    },
    {
      name: {
        text: 'Rosinka ASA Wednesday Years 1-3',
        html: 'Rosinka ASA Wednesday Years 1-3',
      },
      description: {
        text: 'ROSINKA\u00a0Wednesday After School Activities for all students\u00a0in\u00a0Years 1-3\u00a0will start at 15:30 and end at 16:30. The first date of the club is Wednesday 17th January and the last date is Wednesday 14 March 2018. Please click on the club for more details to see if PE kits need to be worn or which equipment you are required to bring.\n\u00a0Full descriptions are not available when viewing on an ipad, so please ensure you view on another device.',
        html: '<P CLASS="MsoNormal"><SPAN>ROSINKA\u00a0Wednesday After School Activities for all students\u00a0in\u00a0Years 1-3\u00a0will start at 15:30 and end at 16:30. The first date of the club is Wednesday 17th January and the last date is Wednesday 14 March 2018. Please click on the club for more details to see if PE kits need to be worn or which equipment you are required to bring.<\/SPAN><SPAN><\/SPAN><\/P>\n<P CLASS="MsoNormal"><SPAN>\u00a0<\/SPAN>Full descriptions are not available when viewing on an ipad, so please ensure you view on another device.<\/P>',
      },
      id: '41057073813',
      url: 'https://www.eventbrite.com/e/rosinka-asa-wednesday-years-1-3-tickets-41057073813?aff=ebapi',
      start: {
        timezone: 'Europe/Moscow',
        local: '2018-01-17T15:30:00',
        utc: '2018-01-17T12:30:00Z',
      },
      end: {
        timezone: 'Europe/Moscow',
        local: '2018-03-14T16:30:00',
        utc: '2018-03-14T13:30:00Z',
      },
      created: '2017-12-05T19:59:34Z',
      changed: '2017-12-11T06:31:31Z',
      capacity: 80,
      capacity_is_custom: true,
      status: 'live',
      currency: 'USD',
      listed: true,
      shareable: true,
      online_event: false,
      tx_time_limit: 480,
      hide_start_date: false,
      hide_end_date: false,
      locale: 'en_US',
      is_locked: false,
      privacy_setting: 'unlocked',
      is_series: false,
      is_series_parent: false,
      is_reserved_seating: false,
      source: 'create_2.0',
      is_free: true,
      version: '3.0.0',
      logo_id: '38427538',
      organizer_id: '2966850589',
      venue_id: '19368286',
      category_id: null,
      subcategory_id: null,
      format_id: null,
      resource_uri: 'https://www.eventbriteapi.com/v3/events/41057073813/',
      logo: {
        crop_mask: {
          top_left: {
            x: 0,
            y: 6,
          },
          width: 254,
          height: 127,
        },
        original: {
          url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F38427538%2F116239082455%2F1%2Foriginal.jpg?s=f2af00b4877c35d8923119a114ecadbe',
          width: 255,
          height: 196,
        },
        id: '38427538',
        url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F38427538%2F116239082455%2F1%2Foriginal.jpg?h=200&w=450&rect=0%2C6%2C254%2C127&s=a819fc42e39c263680903f39ee7d96da',
        aspect_ratio: '2',
        edge_color: null,
        edge_color_set: true,
      },
    },
    {
      name: {
        text: 'Event Marketing School [Virtual Summit]',
        html: 'Event Marketing School [Virtual Summit]',
      },
      description: {
        text: ' The ultimate playbook to triple your revenue, create lifetime customers and dominate your market in 90 days or less.\nThere\u2019s no denying that events drive massive business deals. This summit brings the top 30 event producers and growth marketers to teach the best hacks for growing your business with events. Get ready to discover the fastest channel to acquire and engage customers and 10x ROI.\n\nIn this game-changing virtual event you will learn:\n\nHow to build an engaged community from 0 to 1,000+ members in less than 30 days\n\n\nHow to create lifetime customers from events and dominate your competition.\n\n\nHow to 10x your ROI from events on a shoestring budget.\n\n\nHow to run a profitable in person event from scratch.\n\n\nAccess to the top software tools for virtual and in person events.\n\n\nGrowing brand revenue 300% through event based marketing.\n\n\nGrowth hacks for securing massive email lists from partners.\n\n\nHow to grow a podcast from no audience 1,000% in 6 months.Secrets the general public doesn\u2019t know about ticket pricing.\n\n\nEmail marketing hacks for virutal and in person events.\n\n\nEventBrite hacks that get you in front of thousands of new attendees.\n\n\nHow to get 10,000 new virtual event attendees from LinkedIn.\n\n\nHow to sell a high dollar virtual program to a large audience\n\nThe summit focuses on fundamentals, best practices and unconventional guerilla tactics used by the hottest virtual and in-person events today. (taught by people who are doing it now). 20K+ marketers, industry leading brands, entrepreneurs and event producers will attend.\n\n\n\n\n\n\n\n\nThis summit is packed with LIVE keynotes, never before heard expert panels, and hands-on workshops.\n\n\n',
        html: '<H2><STRONG> The ultimate playbook to triple your revenue, create lifetime customers and dominate your market in 90 days or less.<\/STRONG><\/H2>\n<P><SPAN>There\u2019s no denying that events drive massive business deals. This summit brings the top 30 event producers and growth marketers to teach the best hacks for growing your business with events. Get ready to discover the fastest channel to acquire and engage customers and 10x ROI.<\/SPAN><\/P>\n<P><SPAN><IMG SRC="https://cdn.evbuc.com/eventlogos/201147933/facebookad1.1.jpg"><\/SPAN><\/P>\n<P><SPAN>In this game-changing virtual event you will learn:<\/SPAN><\/P>\n<UL>\n<LI>How to <STRONG>build an engaged community from 0 to 1,000+ members<\/STRONG> in less than 30 days<\/LI>\n<\/UL>\n<UL>\n<LI>How to <STRONG>create lifetime customers<\/STRONG> from events and dominate your competition.<\/LI>\n<\/UL>\n<UL>\n<LI>How to <STRONG>10x your ROI<\/STRONG> from events on a shoestring budget.<\/LI>\n<\/UL>\n<UL>\n<LI>How to run a profitable in person event from scratch.<\/LI>\n<\/UL>\n<UL>\n<LI>Access to the top software tools for virtual and in person events.<\/LI>\n<\/UL>\n<UL>\n<LI>Growing brand revenue 300% through event based marketing.<\/LI>\n<\/UL>\n<UL>\n<LI>Growth hacks for securing massive email lists from partners.<\/LI>\n<\/UL>\n<UL>\n<LI>How to grow a podcast from no audience 1,000% in 6 months.Secrets the general public doesn\u2019t know about ticket pricing.<\/LI>\n<\/UL>\n<UL>\n<LI>Email marketing hacks for virutal and in person events.<\/LI>\n<\/UL>\n<UL>\n<LI>EventBrite hacks that get you in front of thousands of new attendees.<\/LI>\n<\/UL>\n<UL>\n<LI>How to get 10,000 new virtual event attendees from LinkedIn.<\/LI>\n<\/UL>\n<UL>\n<LI>How to sell a high dollar virtual program to a large audience<\/LI>\n<\/UL>\n<P>The summit focuses on fundamentals, best practices and unconventional guerilla tactics used by the hottest virtual and in-person events today. (taught by people who are doing it now). <STRONG>20K+ marketers, industry leading brands, entrepreneurs<\/STRONG> and <STRONG>event producers<\/STRONG> will attend.<BR><\/P>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<P><SPAN><SPAN>This summit is packed with <\/SPAN><SPAN>LIVE keynotes<\/SPAN><SPAN>, never before heard <\/SPAN><SPAN>expert panels, <\/SPAN><SPAN>and<\/SPAN><SPAN> hands-on workshops.<\/SPAN><\/SPAN><BR><\/P>\n<P><SPAN><IMG SRC="https://cdn.evbuc.com/eventlogos/129706179/companieswe27veworkedwith.png"><\/SPAN><\/P>\n<P><BR><\/P>\n<P><IMG SRC="https://cdn.evbuc.com/eventlogos/201147933/screenshot20170215at12.20.12pm.png"><\/P>',
      },
      id: '32248599429',
      url: 'https://www.eventbrite.com/e/event-marketing-school-virtual-summit-tickets-32248599429?aff=ebapi',
      start: {
        timezone: 'Europe/Moscow',
        local: '2017-03-06T10:00:00',
        utc: '2017-03-06T07:00:00Z',
      },
      end: {
        timezone: 'Europe/Moscow',
        local: '2020-06-01T13:00:00',
        utc: '2020-06-01T10:00:00Z',
      },
      created: '2017-02-21T03:38:03Z',
      changed: '2017-03-13T04:18:14Z',
      capacity: 100,
      capacity_is_custom: true,
      status: 'started',
      currency: 'USD',
      listed: true,
      shareable: true,
      online_event: false,
      tx_time_limit: 480,
      hide_start_date: false,
      hide_end_date: false,
      locale: 'en_US',
      is_locked: false,
      privacy_setting: 'unlocked',
      is_series: false,
      is_series_parent: false,
      is_reserved_seating: false,
      source: 'create_2.0',
      is_free: true,
      version: '3.0.0',
      logo_id: '28537818',
      organizer_id: '8193977126',
      venue_id: '18448078',
      category_id: '101',
      subcategory_id: '1001',
      format_id: '11',
      resource_uri: 'https://www.eventbriteapi.com/v3/events/32248599429/',
      logo: {
        crop_mask: {
          top_left: {
            x: 0,
            y: 13,
          },
          width: 1090,
          height: 545,
        },
        original: {
          url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F28537818%2F202555968531%2F1%2Foriginal.jpg?s=a063328fbfbc293dca04b63f90a55b00',
          width: 1091,
          height: 572,
        },
        id: '28537818',
        url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F28537818%2F202555968531%2F1%2Foriginal.jpg?h=200&w=450&rect=0%2C13%2C1090%2C545&s=19ed228385545e5a61387d53d4d40f9b',
        aspect_ratio: '2',
        edge_color: null,
        edge_color_set: true,
      },
    },
    {
      name: {
        text: 'Event Marketing School [Virtual Summit]',
        html: 'Event Marketing School [Virtual Summit]',
      },
      description: {
        text: 'The ultimate playbook to triple your revenue, create lifetime customers and dominate your market in 90 days or less.\nThere\u2019s no denying that events drive massive business deals. This summit brings the top 30 event producers and growth marketers to teach the best hacks for growing your business with events. Get ready to discover the fastest channel to acquire and engage customers and 10x ROI.\n\nIn this game-changing virtual event you will learn:\n\nHow to\u00a0build an engaged community from 0 to 1,000+ members\u00a0in less than 30 days\n\n\nHow to\u00a0create lifetime customers\u00a0from events and dominate your competition.\n\n\nHow to\u00a010x your ROI\u00a0from events on a shoestring budget.\n\n\nHow to run a profitable in person event from scratch.\n\n\nAccess to the top software tools for virtual and in person events.\n\n\nGrowing brand revenue 300% through event based marketing.\n\n\nGrowth hacks for securing massive email lists from partners.\n\n\nHow to grow a podcast from no audience 1,000% in 6 months.Secrets the general public doesn\u2019t know about ticket pricing.\n\n\nEmail marketing hacks for virutal and in person events.\n\n\nEventBrite hacks that get you in front of thousands of new attendees.\n\n\nHow to get 10,000 new virtual event attendees from LinkedIn.\n\n\nHow to sell a high dollar virtual program to a large audience\n\nThe summit focuses on fundamentals, best practices and unconventional guerilla tactics used by the hottest virtual and in-person events today. (taught by people who are doing it now).\u00a020K+ marketers, industry leading brands, entrepreneurs\u00a0and\u00a0event producers\u00a0will attend.\n\n\n\n\n\n\n\n\nThis summit is packed with\u00a0LIVE keynotes, never before heard\u00a0expert panels,\u00a0and\u00a0hands-on workshops.\n\n\n\n',
        html: '<H2><STRONG><BR CLASS="Apple-interchange-newline">The ultimate playbook to triple your revenue, create lifetime customers and dominate your market in 90 days or less.<\/STRONG><\/H2>\n<P>There\u2019s no denying that events drive massive business deals. This summit brings the top 30 event producers and growth marketers to teach the best hacks for growing your business with events. Get ready to discover the fastest channel to acquire and engage customers and 10x ROI.<\/P>\n<P><IMG SRC="https://cdn.evbuc.com/eventlogos/201147933/facebookad1.1.jpg"><\/P>\n<P>In this game-changing virtual event you will learn:<\/P>\n<UL>\n<LI>How to\u00a0<STRONG>build an engaged community from 0 to 1,000+ members<\/STRONG>\u00a0in less than 30 days<\/LI>\n<\/UL>\n<UL>\n<LI>How to\u00a0<STRONG>create lifetime customers<\/STRONG>\u00a0from events and dominate your competition.<\/LI>\n<\/UL>\n<UL>\n<LI>How to\u00a0<STRONG>10x your ROI<\/STRONG>\u00a0from events on a shoestring budget.<\/LI>\n<\/UL>\n<UL>\n<LI>How to run a profitable in person event from scratch.<\/LI>\n<\/UL>\n<UL>\n<LI>Access to the top software tools for virtual and in person events.<\/LI>\n<\/UL>\n<UL>\n<LI>Growing brand revenue 300% through event based marketing.<\/LI>\n<\/UL>\n<UL>\n<LI>Growth hacks for securing massive email lists from partners.<\/LI>\n<\/UL>\n<UL>\n<LI>How to grow a podcast from no audience 1,000% in 6 months.Secrets the general public doesn\u2019t know about ticket pricing.<\/LI>\n<\/UL>\n<UL>\n<LI>Email marketing hacks for virutal and in person events.<\/LI>\n<\/UL>\n<UL>\n<LI>EventBrite hacks that get you in front of thousands of new attendees.<\/LI>\n<\/UL>\n<UL>\n<LI>How to get 10,000 new virtual event attendees from LinkedIn.<\/LI>\n<\/UL>\n<UL>\n<LI>How to sell a high dollar virtual program to a large audience<\/LI>\n<\/UL>\n<P>The summit focuses on fundamentals, best practices and unconventional guerilla tactics used by the hottest virtual and in-person events today. (taught by people who are doing it now).\u00a0<STRONG>20K+ marketers, industry leading brands, entrepreneurs<\/STRONG>\u00a0and\u00a0<STRONG>event producers<\/STRONG>\u00a0will attend.<BR><\/P>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<UL><\/UL>\n<P>This summit is packed with\u00a0LIVE keynotes, never before heard\u00a0expert panels,\u00a0and\u00a0hands-on workshops.<BR><\/P>\n<P><IMG SRC="https://cdn.evbuc.com/eventlogos/129706179/companieswe27veworkedwith.png"><\/P>\n<P><BR><\/P>\n<P><IMG SRC="https://cdn.evbuc.com/eventlogos/201147933/screenshot20170215at12.20.12pm.png"><\/P>\n<P><BR><\/P>',
      },
      id: '27314545541',
      url: 'https://www.eventbrite.com/e/event-marketing-school-virtual-summit-tickets-27314545541?aff=ebapi',
      start: {
        timezone: 'Europe/Moscow',
        local: '2018-03-06T10:30:00',
        utc: '2018-03-06T07:30:00Z',
      },
      end: {
        timezone: 'Europe/Moscow',
        local: '2018-03-09T11:30:00',
        utc: '2018-03-09T08:30:00Z',
      },
      created: '2016-08-24T20:50:33Z',
      changed: '2017-10-22T05:36:08Z',
      capacity: 100,
      capacity_is_custom: true,
      status: 'live',
      currency: 'USD',
      listed: true,
      shareable: true,
      online_event: false,
      tx_time_limit: 480,
      hide_start_date: false,
      hide_end_date: false,
      locale: 'en_US',
      is_locked: false,
      privacy_setting: 'unlocked',
      is_series: false,
      is_series_parent: false,
      is_reserved_seating: false,
      source: 'create_2.0',
      is_free: true,
      version: '3.0.0',
      logo_id: '36872671',
      organizer_id: '10941886782',
      venue_id: '16411994',
      category_id: '101',
      subcategory_id: '1001',
      format_id: '11',
      resource_uri: 'https://www.eventbriteapi.com/v3/events/27314545541/',
      logo: {
        crop_mask: {
          top_left: {
            x: 0,
            y: 13,
          },
          width: 1200,
          height: 600,
        },
        original: {
          url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F36872671%2F105944233453%2F1%2Foriginal.jpg?s=063c88a02d691bbd72f0af48b73b036c',
          width: 1200,
          height: 628,
        },
        id: '36872671',
        url: 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F36872671%2F105944233453%2F1%2Foriginal.jpg?h=200&w=450&rect=0%2C13%2C1200%2C600&s=9f4a3d41165df2b515676cb10e1371c4',
        aspect_ratio: '2',
        edge_color: '#f9f9f9',
        edge_color_set: true,
      },
    },
  ],
  isFetching: false,
}

const events = (state = initialState, action) => {
  switch (action.type) {
    case type.GET_EVENTS:
      return { ...action.data };
    case type.GET_EVENTS_REQUEST:
      return { ...state, isFetching: true }
    case type.GET_EVENTS_SUCCESS:
      return { events: action.data, isFetching: false }
    default: return state;
  }
}

export default events
